Repository beatnaut/remaputils, pull requests merged in 2023-06, with the labels that each got.

#7 Clever email alert job example and related chores
  DESCRIPTION
  NAMESPACE
  R/alerts.R
  R/clever.R
  R/email.R
  data/update_email_template.rda
  install.sh
  var/clever/examples/email-alert/.gitignore
  var/clever/examples/email-alert/README.md
  var/clever/examples/email-alert/config.tmpl.yaml
  var/clever/examples/email-alert/params.json
  var/clever/examples/email-alert/script.R
Labels: bug, enhancement

#8 added spacing to alertnavcomparison fn
  R/alerts.R
Labels: enhancement, good first issue

#9 Andr31 v/outlier fn
  NAMESPACE
  R/nav.R
  man/cleanOutlier.Rd
  man/findOutlier.Rd
  man/outlierEmlTbl.Rd
  man/outlierWrapper.Rd
  man/prefaceSeries.Rd
  man/treatSeries.Rd
Labels: enhancement
